import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/features/Providers";
import { dir } from "i18next";
import i18nConfig from "@/../i18nConfig";
import Paper from "@mui/material/Paper";
import getInitColorSchemeScript from "@mui/system/cssVars/getInitColorSchemeScript";

const fontFamily = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={fontFamily.className}>
        {getInitColorSchemeScript()}
        <Providers params={{ locale }}>
          <Paper className="h-screen rounded-none">{children}</Paper>
        </Providers>
      </body>
    </html>
  );
}
